/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/baseLayout/index.vue";
import BlankLayout from "@/layouts/blankLayout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  account: () => import("@/views/_system/account/index.vue"),
  notification: () => import("@/views/_system/notification/index.vue"),
  setting: () => import("@/views/_system/setting/index.vue"),
  content_blocks: () => import("@/views/content/blocks/index.vue"),
  content_menus: () => import("@/views/content/menus/index.vue"),
  content_pages: () => import("@/views/content/pages/index.vue"),
  content_sections: () => import("@/views/content/sections/index.vue"),
  home: () => import("@/views/home/index.vue"),
  user_permissions: () => import("@/views/user/permissions/index.vue"),
  user_roles: () => import("@/views/user/roles/index.vue"),
  user_users: () => import("@/views/user/users/index.vue"),
};
