/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'account',
    path: '/account',
    component: 'layout.base$view.account',
    meta: {
      title: 'account',
      i18nKey: 'route.account',
      icon: 'ph:user-circle-gear-duotone',
      order: 98
    }
  },
  {
    name: 'content',
    path: '/content',
    component: 'layout.base',
    meta: {
      title: 'content',
      i18nKey: 'route.content',
      icon: 'ph:sidebar-duotone',
      order: 2
    },
    children: [
      {
        name: 'content_blocks',
        path: '/content/blocks',
        component: 'view.content_blocks',
        meta: {
          title: 'content_blocks',
          i18nKey: 'route.content_blocks',
          order: 1,
          icon: 'ph:stack-duotone'
        }
      },
      {
        name: 'content_menus',
        path: '/content/menus',
        component: 'view.content_menus',
        meta: {
          title: 'content_menus',
          i18nKey: 'route.content_menus',
          icon: 'ph:link-simple-duotone',
          order: 3
        }
      },
      {
        name: 'content_pages',
        path: '/content/pages',
        component: 'view.content_pages',
        meta: {
          title: 'content_pages',
          i18nKey: 'route.content_pages',
          icon: 'ph:file-text-duotone',
          order: 4
        }
      },
      {
        name: 'content_sections',
        path: '/content/sections',
        component: 'view.content_sections',
        meta: {
          title: 'content_sections',
          i18nKey: 'route.content_sections',
          icon: 'ph:newspaper-clipping-duotone',
          order: 2
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'ph:desktop-duotone',
      order: 0
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'notification',
    path: '/notification',
    component: 'layout.base$view.notification',
    meta: {
      title: 'notification',
      i18nKey: 'route.notification',
      icon: 'ph:bell-duotone',
      order: 97
    }
  },
  {
    name: 'setting',
    path: '/setting',
    component: 'layout.base$view.setting',
    meta: {
      title: 'setting',
      i18nKey: 'route.setting',
      icon: 'ph:gear-six-duotone',
      order: 99
    }
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: 'user',
      i18nKey: 'route.user',
      icon: 'ph:address-book-duotone',
      order: 3
    },
    children: [
      {
        name: 'user_permissions',
        path: '/user/permissions',
        component: 'view.user_permissions',
        meta: {
          title: 'user_permissions',
          i18nKey: 'route.user_permissions',
          icon: 'ph:key-duotone',
          order: 3
        }
      },
      {
        name: 'user_roles',
        path: '/user/roles',
        component: 'view.user_roles',
        meta: {
          title: 'user_roles',
          i18nKey: 'route.user_roles',
          icon: 'ph:shield-duotone',
          order: 2
        }
      },
      {
        name: 'user_users',
        path: '/user/users',
        component: 'view.user_users',
        meta: {
          title: 'user_users',
          i18nKey: 'route.user_users',
          icon: 'ph:users-duotone',
          order: 1
        }
      }
    ]
  }
];
